//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.12 at 12:40:10 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/warehouse", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package SC13Project.Milestone1.Warehouse.Database;
